// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type User struct {
	ID             []byte
	Username       string
	Displayname    sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
}
